<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<groupId>com.framework.api</groupId>
	<artifactId>RestAssured-Framework</artifactId>
	<version>0.0.1-SNAPSHOT</version>

	<properties>
		<!-- Compiler and plugins -->
		<maven.compiler.source>11</maven.compiler.source>
		<maven.compiler.target>11</maven.compiler.target>
		<maven.compiler.release>11</maven.compiler.release>
		<maven.compiler.version>3.11.0</maven.compiler.version>
		<maven.surefire.version>3.2.3</maven.surefire.version>

		<!-- Dependencies -->
		<testng.version>7.11.0</testng.version>
		<rest-assured.version>5.1.1</rest-assured.version>
		<json.version>20220320</json.version>
		<java-faker.version>1.0.2</java-faker.version>
		<scribejava-apis.version>8.3.1</scribejava-apis.version>
		<jackson-databind-version>2.18.2</jackson-databind-version>
		<log4j.version>2.22.1</log4j.version>
		<slf4j.version>1.7.36</slf4j.version>
		<reportng.version>2.7.0</reportng.version>

		<!-- testNG suite xml file -->
		<api.test.suites>api-tests.xml</api.test.suites>
	</properties>

	<dependencies>
		<!-- TestNG -->
		<dependency>
			<groupId>org.testng</groupId>
			<artifactId>testng</artifactId>
			<version>${testng.version}</version>
		</dependency>

		<!-- Rest Assured Core -->
		<dependency>
			<groupId>io.rest-assured</groupId>
			<artifactId>rest-assured</artifactId>
			<version>${rest-assured.version}</version>
		</dependency>

		<!-- Rest Assured Modules -->
		<dependency>
			<groupId>io.rest-assured</groupId>
			<artifactId>json-path</artifactId>
			<version>${rest-assured.version}</version>
		</dependency>

		<dependency>
			<groupId>io.rest-assured</groupId>
			<artifactId>json-schema-validator</artifactId>
			<version>${rest-assured.version}</version>
		</dependency>

		<!-- JSON Libraries -->
		<dependency>
			<groupId>org.json</groupId>
			<artifactId>json</artifactId>
			<version>${json.version}</version>
		</dependency>

		<dependency>
			<groupId>com.fasterxml.jackson.core</groupId>
			<artifactId>jackson-databind</artifactId>
			<version>${jackson-databind-version}</version>
		</dependency>

		<!-- For Generating fake/dummy data  -->
		<dependency>
			<groupId>com.github.javafaker</groupId>
			<artifactId>javafaker</artifactId>
			<version>${java-faker.version}</version>
		</dependency>

		<!-- Logging -->
		<dependency>
			<groupId>org.apache.logging.log4j</groupId>
			<artifactId>log4j-core</artifactId>
			<version>${log4j.version}</version>
		</dependency>
		<dependency>
			<groupId>org.apache.logging.log4j</groupId>
			<artifactId>log4j-slf4j-impl</artifactId>
			<version>${log4j.version}</version>
		</dependency>
		<dependency>
			<groupId>org.slf4j</groupId>
			<artifactId>slf4j-api</artifactId>
			<version>${slf4j.version}</version>
		</dependency>

		<!-- ReportNG -->
		<dependency>
			<groupId>com.github.sdrss</groupId>
			<artifactId>reportng</artifactId>
			<version>${reportng.version}</version>
		</dependency>
	</dependencies>

	<build>
		<plugins>
			<!-- Maven Compiler Plugin -->
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-compiler-plugin</artifactId>
				<version>${maven.compiler.version}</version>
				<configuration>
					<source>${maven.compiler.source}</source>
					<target>${maven.compiler.target}</target>
					<release>${maven.compiler.release}</release>
				</configuration>
			</plugin>

			<!-- Maven Surefire Plugin -->
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-surefire-plugin</artifactId>
				<version>${maven.surefire.version}</version>
				<configuration>
					<suiteXmlFiles>
						<suiteXmlFile>${api.test.suites}</suiteXmlFile>
					</suiteXmlFiles>
					<systemPropertyVariables>
						<org.uncommons.reportng.logOutputReport>true</org.uncommons.reportng.logOutputReport>
					</systemPropertyVariables>
					<properties>
						<property>
							<name>listener</name>
							<value>
								org.uncommons.reportng.HTMLReporter,org.uncommons.reportng.JUnitXMLReporter</value>
						</property>
					</properties>
				</configuration>
			</plugin>
		</plugins>
	</build>
</project>
