name: API Test Pipeline

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Set up Docker Compose
        uses: docker/setup-compose-action@v1
      
      - name: Start API and Run Tests
        run: |
          docker compose up --build --exit-code-from test-petstore
      
      - name: Copy Test Results
        if: always()
        run: |
          mkdir -p test-results
          find . -path "*/target/surefire-reports" -type d -exec cp -r {} ./test-results \; || true
      
      - name: Publish Test Report
        uses: dorny/test-reporter@v2
        if: always()
        with:
          name: TestNG Results
          path: ./test-results/TEST-*.xml
          reporter: java-junit
      
      - name: Upload HTML Reports
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: Test Execution Report
          path: ./test-results/html/index.html
          retention-days: 7